---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url:
sections:
- type: document
  path: src/assets/content/data/info.json
  label: Info Page
- type: document
  path: src/assets/content/data/home.json
  label: Home Page
- type: document
  path: src/assets/content/data/config.json
  label: Site Config
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path:
file_template: ":filename:"
build:
  preview_env:
  - GRAPHQL_ENDPOINT=/___graphql
  preview_output_directory: src/
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
